// Parser for NPNQM's engine-generated Document_Requirements_All_Income_Types.md.
// See spec docs/superpowers/specs/2026-05-12-doc-checklist-ingest-design.md
// §1 (source artifact) and §5 (parser design).
//
// Deterministic, no LLM. Uses marked AST. Each parser scopes to a single
// "File Section" of the source markdown (A/B/C/D — see spec §1.1).

import { createHash } from "node:crypto";
import { marked, type Tokens } from "marked";

// ── Public types ───────────────────────────────────────────────────────────

export interface DocItem {
  order: number;
  name: string;
  note: string | null;
}

export interface ScenarioRow {
  resolved_income_type: string;
  program: string;
  minimum_docs: DocItem[];
  income_docs: DocItem[];
  raw_min_msg: string;
  raw_income_msg: string;
}

export type RuleName = "llc_closing_docs" | "field_review" | "us_credit_optional";

export interface RuleRow {
  rule_name: RuleName;
  predicate: Record<string, unknown>;
  effect: { add_docs: string[]; remove_docs: string[] };
  description: string;
}

export interface ResolverRow {
  income_doc_type: string;
  borrower_type: "W2" | "Self-Employed";
  citizenship: "US Citizen" | "Foreign Nationals";
  is_itin: boolean;
  resolved_income_type: string;
}

export interface ParseResult {
  scenarios: ScenarioRow[];
  rules: RuleRow[];
  resolver: ResolverRow[];
  generatedAt: string;     // ISO from the footer
  sourceHash: string;      // sha256 of the input markdown
}

// ── Errors ─────────────────────────────────────────────────────────────────

export class DocChecklistParseError extends Error {
  constructor(message: string, public readonly section: "A" | "B" | "C" | "D" | "footer") {
    super(message);
    this.name = "DocChecklistParseError";
  }
}

// ── Entry points (impl follows in later tasks) ─────────────────────────────

export function parseScenarios(markdown: string): ScenarioRow[] {
  throw new Error("parseScenarios not yet implemented");
}

export function parseEngineRules(markdown: string): RuleRow[] {
  throw new Error("parseEngineRules not yet implemented");
}

export function parseResolverTable(markdown: string): ResolverRow[] {
  throw new Error("parseResolverTable not yet implemented");
}

export function parseAll(markdown: string): ParseResult {
  const scenarios = parseScenarios(markdown);
  const rules = parseEngineRules(markdown);
  const resolver = parseResolverTable(markdown);
  const footerMatch = markdown.match(/_Generated by [^\s]+ at (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})_/);
  if (!footerMatch) {
    throw new DocChecklistParseError(
      "missing generation timestamp footer (expected `_Generated by ... at YYYY-MM-DD HH:MM:SS_`)",
      "footer",
    );
  }
  const generatedAt = new Date(footerMatch[1]!.replace(" ", "T") + "Z").toISOString();
  const sourceHash = createHash("sha256").update(markdown).digest("hex");
  return { scenarios, rules, resolver, generatedAt, sourceHash };
}

// ── Internal helpers used by multiple parsers ──────────────────────────────

/** Walk a marked AST, yielding only top-level heading tokens with text. */
export function* iterHeadings(tokens: Tokens.Generic[]): Generator<{ depth: number; text: string; index: number }> {
  for (let i = 0; i < tokens.length; i++) {
    const t = tokens[i]!;
    if (t.type === "heading") {
      yield { depth: (t as Tokens.Heading).depth, text: (t as Tokens.Heading).text, index: i };
    }
  }
}

/** Verify the input parses to a non-empty marked AST. Throws DocChecklistParseError otherwise. */
export function parseAst(markdown: string): Tokens.Generic[] {
  const tokens = marked.lexer(markdown);
  if (!tokens || tokens.length === 0) {
    throw new DocChecklistParseError("empty markdown input", "A");
  }
  return tokens;
}
